function DebugWindow(appHandle)
if isempty(findobj('Name','Debug Window'))
    set(0,'Units','centimeters')
    pos = get(0,'ScreenSize');

    debugfig = figure('Units','centimeters',...
        'Position',[pos(3)-6.1 2 6 4],...
        'Color',[0.831 0.816 0.784],...
        'Name','Debug Window',...
        'NumberTitle','off',...
        'MenuBar','none');

    uicontrol(debugfig,'Units','centimeters',...
        'Style','pushbutton',...
        'Position',[0 1.75 1.5 0.5],...
        'String','Left',...
        'Callback',{@leftButton_callback , appHandle});
    uicontrol(debugfig,'Units','centimeters',...
        'Style','pushbutton',...
        'Position',[4.5 1.75 1.5 0.5],...
        'String','Right',...
        'Callback',{@rightButton_callback , appHandle});
    uicontrol(debugfig,'Units','centimeters',...
        'Style','pushbutton',...
        'Position',[2.25 1.75 1.5 0.5],...
        'String','Start',...
        'Callback',{@startButton_callback , appHandle});
    uicontrol(debugfig,'Units','centimeters',...
        'Style','pushbutton',...
        'Position',[2.25 3.5 1.5 0.5],... 
        'String','Up',...
        'Callback',{@upButton_callback , appHandle});
    uicontrol(debugfig,'Units','centimeters',...    
        'Style','pushbutton',...
        'Position',[2.25 0 1.5 0.5],... 
        'String','Down',...
        'Callback',{@downButton_callback , appHandle});
end

function leftButton_callback(hobject, event_data ,handle) 
debugResponse = 'd';
setappdata(handle , 'debugResponse' , debugResponse);
display('setttttttttttttttttttttttttttttttttttttttttted');

function rightButton_callback(hobject, event_data ,handle)
debugResponse = 'f';
setappdata(handle , 'debugResponse' , debugResponse);
display('setttttttttttttttttttttttttttttttttttttttttted');

function startButton_callback(hobject, event_data , handle)
debugResponse = 's';
setappdata(handle , 'debugResponse' , debugResponse);
display('setttttttttttttttttttttttttttttttttttttttttted');

function upButton_callback(hobject, event_data ,handle)
debugResponse = 'e';
setappdata(handle , 'debugResponse' , debugResponse);
display('setttttttttttttttttttttttttttttttttttttttttted');

function downButton_callback(hobject, event_data ,handle) 
debugResponse = 'x';
setappdata(handle , 'debugResponse' , debugResponse);
display('setttttttttttttttttttttttttttttttttttttttttted');