function DebugWindow

if isempty(findobj('Name','Debug Window'))
    set(0,'Units','centimeters')
    pos = get(0,'ScreenSize');

    debugfig = figure('Units','centimeters',...
        'Position',[pos(3)-6.1 2 6 4],...
        'Color',[0.831 0.816 0.784],...
        'Name','Debug Window',...
        'NumberTitle','off',...
        'MenuBar','none');

    uicontrol(debugfig,'Units','centimeters',...
        'Style','pushbutton',...
        'Position',[0 1.75 1.5 0.5],...
        'String','Left',...
        'Callback',{@leftButton_callback});
    uicontrol(debugfig,'Units','centimeters',...
        'Style','pushbutton',...
        'Position',[4.5 1.75 1.5 0.5],...
        'String','Right',...
        'Callback',{@rightButton_callback});
    uicontrol(debugfig,'Units','centimeters',...
        'Style','pushbutton',...
        'Position',[2.25 1.75 1.5 0.5],...
        'String','Start',...
        'Callback',{@startButton_callback});
    uicontrol(debugfig,'Units','centimeters',...
        'Style','pushbutton',...
        'Position',[2.25 3.5 1.5 0.5],... 
        'String','Up',...
        'Callback',{@upButton_callback});
    uicontrol(debugfig,'Units','centimeters',...    
        'Style','pushbutton',...
        'Position',[2.25 0 1.5 0.5],... 
        'String','Down',...
        'Callback',{@downButton_callback});
end

function leftButton_callback(hObject, eventdata)
global in 
in = 'd';

function rightButton_callback(hObject, eventdata)
global in 
in = 'f';

function startButton_callback(hObject, eventdata)
global in 
in = 's';


function upButton_callback(hObject, eventdata)
global in 
in = 'e';

function downButton_callback(hObject, eventdata)
global in 
in = 'x';